---
name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"

jobs:
  Deploy-to-docker:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t wallet-telegrambot .
      - name: Stop old instance
        run: docker rm --force wallet-telegrambot
      - name: Deploy
        run: >
          docker run 
          --name wallet-telegrambot 
          -e API_KEY="${{ secrets.API_KEY }}" 
          -e WALLET_BASE_URL="${{ secrets.WALLET_BASE_URL }}" 
          -e WALLET_API_KEY="${{ secrets.WALLET_API_KEY }}" 
          --restart unless-stopped -d 
          wallet-telegrambot
      - name: Clean up
        run: docker rmi $(docker images -f "dangling=true" -q)
